# Generated by Django 5.2.4 on 2025-07-31 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_practicalquestion_practicalanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeexam',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='trainee_exam_images/'),
        ),
        migrations.AddField(
            model_name='traineeexam',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
