# Generated by Django 5.2.4 on 2025-10-03 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS_Admin_Portal', '0009_course_end_date_course_start_date'),
        ('exam', '0005_remove_exam_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VTS_Admin_Portal.trainer'),
            preserve_default=False,
        ),
    ]
