# Generated by Django 5.2.4 on 2025-10-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_exam_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='trainer',
        ),
    ]
