# Generated by Django 5.2.4 on 2025-10-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS_Admin_Portal', '0009_course_end_date_course_start_date'),
        ('exam', '0011_remove_exam_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='trainer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VTS_Admin_Portal.trainer'),
        ),
    ]
