# Generated by Django 5.2.4 on 2025-10-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_exam_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='isActivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
    ]
