# Generated by Django 5.2.4 on 2025-10-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_exam_isactivate_exam_isexpired'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalquestion',
            name='isActivate',
            field=models.BooleanField(default=False),
        ),
    ]
