# Generated by Django 5.2.4 on 2025-10-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_practicalquestion_isactivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeexam',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='trainee_exam_videos/'),
        ),
        migrations.AlterField(
            model_name='practicalquestion',
            name='isActivate',
            field=models.BooleanField(default=True),
        ),
    ]
