# Generated by Django 5.2.4 on 2025-07-14 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS_Admin_Portal', '0008_trainee_class_mode'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question_pdf', models.FileField(upload_to='practical_questions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VTS_Admin_Portal.course')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_pdf', models.FileField(upload_to='practical_answers/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VTS_Admin_Portal.trainee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.practicalquestion')),
            ],
        ),
    ]
