# Generated by Django 5.2.4 on 2025-07-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VTS_Admin_Portal', '0003_alter_user_full_name_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='profile_picture',
        ),
    ]
