# Generated by Django 5.2.4 on 2025-07-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS_Admin_Portal', '0005_course_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='expertise_area',
            field=models.CharField(choices=[('Designing', 'Designing'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack')], max_length=20),
        ),
    ]
