# Generated by Django 5.2.4 on 2025-07-07 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS_Admin_Portal', '0006_alter_trainer_expertise_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='trainee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
