# Generated by Django 5.2.4 on 2025-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS_Admin_Portal', '0007_remove_course_end_date_remove_course_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='class_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10),
        ),
    ]
